### PR TITLE
Solid wrapper

### PR DESCRIPTION
**Pull request by LiamMartens**
Adds a package for `Solid-JS` support. Also includes docs for it.

- Closes: #429.

### CODE REVIEW

**Comment by davidjerleke** [comment]
@LiamMartens thank you for your great contribution 🎉. I have a lot in the pipe now before I can review this PR so thank you for your patience.

Best,
David

**Comment by davidjerleke** [comment]
@LiamMartens I have a little left to test on this PR and I want to let you know that this is great! I will make some small adjustments to align some things with the other existing wrappers like React, Vue and Svelte.

Soon Embla will have a SolidJS wrapper published 🎉. I want to put your name on the SolidJS wrapper if that’s ok?

**Review by davidjerleke — APPROVED** [review]
Fantastic ⭐. Thank you @LiamMartens!

**Comment by LiamMartens** [comment]
Awesome thanks for having a look and merging! @davidjerleke

**Pull request merged**
