### PR TITLE
Angular wrapper (new)

### PR DESCRIPTION
**Pull request by donaldxdonald**
Hi @davidjerleke ,

Long time no talk! I apologize for the delay, as I've been quite busy lately. I wanted to let you know that I've finished all the Angular wrapper code and documentation. It's all ready for review. The context is here #18 .

- [x] embla-carousel-angular
- [x] embla-carousel-playground-angular
- [x] docs/get-started/angular 

There are a few points that need to be clarified:

### Bundling

> All library wrapper packages have the same rollup.js structure which bundles the code.

Angular has its own webpack-based Angular CLI for bundling, and since the Angular ecosystem is almost exclusively packaged using the Angular CLI, it makes more sense to use it for bundling.

### Publishing

As mentioned above, `embla-carousel-angular` is packaged using the Angular CLI, which outputs the build to the `dist` folder (or some other non-root path).

All other libraries in the `embla-carousel` repository are packaged with rollup and exported directly to the root directory of the library, and then the `npm publish` command is executed in CI/CD, which is not directly usable in `embla-carousel-angular`.

So I've changed the release command in `cd.yml` to run **`yarn release`** so that I can use a specific release strategy for each library.

Thank you for your patience, and once again, I apologize for the delay. I appreciate your continued support and guidance throughout this process.

### CODE REVIEW

**Comment by davidjerleke** [comment]
Hi @donaldxdonald,

Thank you for your efforts. This is great! And no worries. As I mentioned there’s no deadline involved. I’m just happy that you want to contribute 🙂. 

I will review this PR as soon as possible. I just want to mention that I have two things I’ve started that I want to finish before jumping into this. Thank you for your patience!

Best,
David

**Comment by davidjerleke** [comment]
Hi @donaldxdonald,

I'm done with the two other things now. If you rebase your branch/changes on my `master` branch I will review this PR afterwards.

Thanks!
David

**Comment by donaldxdonald** [comment]
Done. @davidjerleke

**Comment by davidjerleke** [comment]
Hi @donaldxdonald!

Hope you're doing great. I caught Covid so been off for some time but I'm back now and I just started looking into this PR. Please refrain from pushing new stuff until I'm done. Thanks for understanding 🙂.

Best,
David

**Comment by davidjerleke** [comment]
@donaldxdonald closing this because I've updated the original (first) Angular PR and fixed the git history there. Don't worry, all changes in this branch are there now:

- #627

**Pull request closed without merging**
