### PR TITLE
Add TypeScript usage examples to the docs

### PR DESCRIPTION
**Pull request by zaaakher**
Added typescript page for the docs

--- 

This is just a starting point since I had to wing it since I couldn't get the gatspy docs running locally in my PC. I will add more when I get the chance god willing

### CODE REVIEW

**Comment by davidjerleke** [comment]
Note: We need to [add this](https://github.com/davidjerleke/embla-carousel/issues/647#issuecomment-1868273239) to the docs.

**Comment by zaaakher** [comment]
@davidjerleke I finalized the typescript page and also updated the way types are imported in the Sandboxes.

Kindly take a look at it and let me know you need additional help 👍

**Comment by zaaakher** [comment]
Hey @davidjerleke ,

I've been working on my UI kit library [here](https://github.com/sikka-software/hawa) and I have the carousel component working well with only using `embla-carousel-react` package. Now that the types will move into `embla-carousel` package, does that mean I have to install it just to use the types? would it be bad to install `embla-carousel` as a devDependency? 

Or should we look into making a PR for creating a `@types/embla-carousel` package in [this repo](https://github.com/DefinitelyTyped/DefinitelyTyped)?

Or would it be strategic to make a package solely for the types? like `embla-carousel-types` ?

Based on your comment [here](https://github.com/davidjerleke/embla-carousel/issues/647#issuecomment-1868273239) , `embla-carousel` should be a dependency but somehow I got the carousel working without `embla-carousel` and with only the react wrapper (here's my [package.json](https://github.com/sikka-software/Hawa/blob/a13896076dc51241df9ce3f464a2fc4a0b23e36a/package.json#L89))

**Comment by davidjerleke** [comment]
@zaaakher `embla-carousel-react` has `embla-carousel` as a dependency, so when you install the react package it will automatically install the core package under the hood. You can easily confirm this like so:

- Install `embla-carousel-react`.
- Expand the `node_modules` folder.
- Scroll down to `e` and see both embla packages there: `embla-carousel-react` and `embla-carousel`.

So you should import types from the core package `embla-carousel`. I will remove any type re-exports from all library/framework packages in the next release.

I hope my explanation makes sense?

Best,
David

**Comment by zaaakher** [comment]
> I don’t think it’s common practice to make a separate types package because Embla has first class TypeScript support. It’s built with TypeScript. I think type packages are mainly used for packages built without TypeScript.

True true, I agree.

---

> `embla-carousel-react` has `embla-carousel` as a dependency, so when you install the react package it will automatically install the core package under the hood

That doesn't seem to be working as expected when using pnpm workspace

in my project [here](https://github.com/sikka-software/Hawa) I can do as you mentioned and everything works fine.

But currently i'm migrating to a proper monorepo structure using pnpm (in the [monorepo branch](https://github.com/sikka-software/Hawa/tree/monorepo)) and it seems `embla-carousel` is not recognized.

image

**Comment by zaaakher** [comment]
Looking at [this](https://github.com/pnpm/pnpm/issues/2903) I was able to find `embla-carousel` in the root `node_modules` inside `.pnpm` but doing the following won't work and doesn't even look right.
```
import { EmblaOptionsType } from "../../../../node_modules/.pnpm/embla-carousel@8.0.0-rc17";
```

It's most likely a `pnpm` thing but I think it could be an important caveat to include somewhere in this library.

**Comment by zaaakher** [comment]
shadcn-ui is using this library but they still [didn't migrate](https://github.com/search?q=repo%3Ashadcn-ui%2Fui%20embla-carousel&type=code) to the new typescript approach. And they're using `pnpm` as well. 

So there's a chance they might stumble upon a similar problem if not an identical one to mine as they update embla as per your suggestion [here](https://github.com/shadcn-ui/ui/discussions/2146) and change the way they import types. 

Of course a simple solution would be to explicitly install `embla-carousel` but I'm inclined to resist to do that.

**Comment by davidjerleke** [comment]
@zaaakher that’s valuable information. Thank you. I haven’t used `pnpm` so didn’t know about this. If this is the case, the solution would be to copy over the types from the core package to the library wrappers during the build process. Are there anymore things to consider to fully support `pnpm`?

**Comment by zaaakher** [comment]
> Are there anymore things to consider to fully support pnpm?

Making `embla-carousel` a peer dependency of `embla-carousel-react` could potentially solve this problem (I'm not entirely sure if it will). But would doing that cause problems elsewhere?

**Comment by davidjerleke** [comment]
> Making `embla-carousel` a peer dependency of `embla-carousel-react` could potentially solve this problem (I'm not entirely sure if it will). But would doing that cause problems elsewhere?

@zaaakher I’m not sure how that would affect npm/yarn and pnpm for that matter…

**Comment by zaaakher** [comment]
> Is that a conventional solution?

It doesn't feel like it and i'm very doubtful if it'd work.

> the solution would be to copy over the types from the core package to the library wrappers during the build process

That's a good solution, I can't think of a better one at the moment. Although is there a possible scenario in the future where a library wrapper uses a slightly different type from the one in the core library? (i.e. something unique to react or vue or server components) 

Currently I'm using types the original way 👇
```jsx
import useEmblaCarousel, { EmblaOptionsType } from "embla-carousel-react";
```
I think it could be a good developer experience when consumers of this library have to install a single package (depending on their framework) where they can import hooks, types, and possibly components. 

Honestly I never knew I could import from a package that's not listed in my package.json, I just learned I could do that from you 😄 (although that didn't work with pnpm).

I wish I have more time on my hand to test it out with pnpm alternatives like [lerna](https://lerna.js.org/), [rush](https://rushjs.io/), or [bolt](https://github.com/boltpkg/bolt). Nevertheless, I have a feeling they all have a similar approach to how they put aside dependencies-of-dependencies to save disk space and increase performance within a monorepo structure.

I understand there could be performance/size trade-offs depending on the approach you'd like to take and I'm here if you wanna bounce ideas around, I'm just thinking out loud.

**Comment by davidjerleke** [comment]
@zaaakher I will try the copy types approach then. Thanks for your thoughts 👍🏻.

Wow. The frontend tooling world is so broken. It’s really a nightmare to try to support everything. Feels like we spend 95% of our time with tools…

**Comment by zaaakher** [comment]
> Wow. The frontend tooling world is so broken. It’s really a nightmare to try to support everything. Feels like we spend 95% of our time with tools…

True. It's the same cycle where an individual or a group of people make tool, then it gains popularity, then it's a either they have to start adapting to others or others have to adapt to them.

**Comment by mulfyx** [comment]
Workaround:

```ts
import { UseEmblaCarouselType } from "embla-carousel-react";

type EmblaCarouselType = NonNullable<UseEmblaCarouselType[1]>;
```

**Comment by davidjerleke** [comment]
@zaaakher again, thanks for all your contributions and making this library better 🌟!

**Comment by zaaakher** [comment]
@davidjerleke You're very welcome brother 🌹

**Comment by mulfyx** [comment]
i think you miss something

image

**Comment by zaaakher** [comment]
Yup @mulfyx , it'll be fixed with #685

**Pull request merged**
