### PR TITLE
Relocating `CONTRIBUTING.md` to root directory

### PR DESCRIPTION
**Pull request by zaaakher**
Moved `CONTRIBUTING.md` to the root directory as suggested in this [comment](https://github.com/davidjerleke/embla-carousel/pull/671#issuecomment-1879794857)

### CODE REVIEW

**Comment by davidjerleke** [comment]
Thanks again @zaaakher ⭐!

**Comment by zaaakher** [comment]
@davidjerleke You're welcome brother 👍

**Comment by zaaakher** [comment]
image

I thought these tabs were based on the `.md` files in the root directory but it turns out to be pre-determined for the following files only:
- README.md
- CODE_OF_CONDUCT.md
- LICENSE
- SECURITY.md

It's not a problem anyway 😁



didnt-know

**Comment by davidjerleke** [comment]
> image
> 
> I thought these tabs were based on the `.md` files in the root directory but it turns out to be pre-determined for the following files only:
> 
> * README.md
> * CODE_OF_CONDUCT.md
> * LICENSE
> * SECURITY.md
> 
> It's not a problem anyway 😁
> 
> didnt-know [ didnt-know ](https://camo.githubusercontent.com/8b55b8d537f15ac0e23399708f7aadefd2a2b61732641af30d0e03e5ff7ffa55/68747470733a2f2f6d65646961312e74656e6f722e636f6d2f6d2f7976486e3459383548476341414141432f692d6469646e742d6576656e2e676966) [ ](https://camo.githubusercontent.com/8b55b8d537f15ac0e23399708f7aadefd2a2b61732641af30d0e03e5ff7ffa55/68747470733a2f2f6d65646961312e74656e6f722e636f6d2f6d2f7976486e3459383548476341414141432f692d6469646e742d6576656e2e676966)

@zaaakher no problem at all! It seems to be convention to have the `CONTRIBUTING.md` in the project root anyway so thanks 🙂.

**Pull request merged**
